committing

diff --git a/15-loops b/15-loops
--- a/15-loops
+++ b/15-loops
@@ -13,12 +13,20 @@ if [ $userid -ne 0 ]; then
     echo "ERROR please run the script with sudo privillages"
     exit 1
 fi
-validate(){
+# validate(){
+#     if [ $1 -ne 0 ]; then
+#         echo -e "installation of $2...... $R failed $N" | tee -a $log_file
+#         exit 1
+#     else
+#         echo -e "installation of $2......$G success $N" | tee -a $log_file
+#     fi
+#}
+VALIDATE(){ # functions receive inputs through args just like shell script args
     if [ $1 -ne 0 ]; then
-        echo -e "installation of $2...... $R failed $N" | tee -a $log_file
+        echo -e "Installing $2 ... $R FAILURE $N" | tee -a $log_file
         exit 1
     else
-        echo -e "installation of $2......$G success $N" | tee -a $log_file
+        echo -e "Installing $2 ... $G SUCCESS $N" | tee -a $log_file
     fi
 }
 for package in $@
