committing

diff --git a/9-installation b/9-installation
--- a/9-installation
+++ b/9-installation
@@ -5,7 +5,7 @@ if [ $userid -ne 0 ]; then
 	exit 1
 fi
 dnf install nginx -y
-if [ $? -ne 0 ]; then 
+if [ $? -ne 0 ]; then #here $? is exit status of last command
 	echo "ERROR: installation of nginx is failed"
 	exit 1
 else 
